sudo: false
language: python
python:
  - "3.5"
  - "3.6-dev"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - travis_retry pip install coverage codecov
script:
  - coverage run -m unittest discover -t ../
after_success:
  - coverage report
  - codecov
